changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Fixes
      labels:
        - fix
        - bug
    - title: 🧰 Maintenance
      labels:
        - chore
        - dependencies
    - title: Other Changes
      labels:
        - "*"
